### PR TITLE
ci: remove Travis CI workflow

### PR DESCRIPTION
**Pull request by MikeMcC399**
## Issue

- The CI workflow defined by [.travis.yml](https://github.com/indexzero/ps-tree/blob/master/.travis.yml) is outdated and unused.
- The [README](https://github.com/indexzero/ps-tree/blob/master/README.md) badge [Build Status](https://travis-ci.org/indexzero/ps-tree) links to https://travis-ci.org/indexzero/ps-tree which displays the message "This repository may not exist or you may need to Sign in". The badge itself displays an "unknown" status.
- CI checks on Linux and osx (now macOS) are now carried out with the GitHub Actions workflow [ci-test.yml](https://github.com/indexzero/ps-tree/actions/workflows/ci-test.yml)

## Change

1. Remove the [.travis.yml](https://github.com/indexzero/ps-tree/blob/master/.travis.yml) workflow.
2. Replace the `build: status` badge in the [README](https://github.com/indexzero/ps-tree/blob/master/README.md) file using a badge linked to the functioning GitHub Actions workflow https://github.com/indexzero/ps-tree/actions/workflows/ci-test.yml build status

## Reference

[Adding a workflow status badge](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge)

## Follow-on action

- Check if there is a need to delete any remaining information or account data from https://app.travis-ci.com/indexzero/ps-tree

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Preview

https://github.com/MikeMcC399/ps-tree/blob/remove/ci-travis/README.md

**Review by nelsonic — APPROVED** [review]
Thanks for removing the `.travis.yml` file as their service no longer supports older versions of `Node.js` ✅  
[Build Status](https://travis-ci.org/indexzero/ps-tree)

**Comment by MikeMcC399** [comment]
@MikeMcC399 
> Thanks for removing the `.travis.yml` file 

You are welcome!

> as their service no longer supports older versions of `Node.js` ✅ 

I believe that Travis CI was failing because there was no longer an active subscription to the service. AFAIK they support all available versions of Node.js, which includes older ones.

**Comment by nelsonic** [comment]
@MikeMcC399 since `Travis CI` was sold to `Private Equity` 
https://techcrunch.com/2019/01/23/idera-acquires-travis-ci/ 🤦‍♂️ 
they have gone downhill and broken the builds of many Open Source projects ... 💔 
We had to remove from _many_ repos: https://github.com/dwyl/learn-travis/issues/67 😢 
`PE` has to make their profits/bonuses so they cut the "freeloaders" (that helped _build_ the service...!) ✂️ 
So now `GitHub Actions CI` is all we use. ✅ 

Again, thanks for helping to spring-clean / update this project. 👌

**Comment by MikeMcC399** [comment]
@nelsonic 

Thanks for the background on Travis CI! Now I know why they don't get used in Open Source repos anymore.

**Pull request merged**
