### PR TITLE
Better support for Darwin/Mac

### PR DESCRIPTION
**Pull request by huan**
see #18

### CODE REVIEW

**Comment by zixia** [comment]
could we accept this? then I could pull new pr for 'COMM' & 'COMMAND'

**Comment by johanneswuerbach** [comment]
Any help needed @indexzero / @zixia ? I would also like to see this merged.

**Comment by soyuka** [comment]
nice work, would be great if it'd get merged! @indexzero any way you could add some ppl as collaborators? Thanks!

**Comment by simonepri** [comment]
@indexzero any news on this?

**Comment by simonepri** [comment]
@zixia we can close this in favour of #29

**Comment by simonepri** [comment]
@zixia Can you add a section inside the readme under `Cross Platform support` for darwin?

**Comment by zixia** [comment]
@simonepri done.

**Comment by simonepri** [comment]
LGTM!

**Pull request merged**
