### PR TITLE
Win32 platform support

### PR DESCRIPTION
**Pull request by zixia**
@indexzero I had just finished a runable win32 version of ps-tree, include the following changes:

# Code:
1. use `wmic.exe` to simulate `ps` under win32 platform.
1. map output header of wmic to ps
1. strip the linux ` <defunct> ` from the output

# Test
1. modify `istanbul` command line to support win32
1. use npm module `tree-kill` to replace the `kill` to support win32
1. use npm module `cross-env` to enable set environment variable in package.json

Hope this helps. :)

### CODE REVIEW

**Comment by zixia** [comment]
See also #13

**Comment by indexzero** [comment]
This looks good. Will review and try to merge this weekend.

**Comment by zixia** [comment]
@indexzero how about the process? I need the new npm package to enable my code to support win32. :)

**Comment by indexzero** [comment]
@zixia merged this with some minor changes. The biggest thing in your PR that I need help from you with is getting Appveyor working. TravisCI does not support Windows so adding `windows` in `.travis.yml` did not add WIndows CI support.

Could you help me setup Windows CI on this project? Thanks again for your contribution!

**Comment by zixia** [comment]
cool. I'll pay attention on win32 ci... it seems there's no existing ci service to provide win32, it's funny.

**Comment by indexzero** [comment]
Appveyor CI does work with Windows. https://www.appveyor.com/

**Comment by zixia** [comment]
great. I'm working on it now, it's pretty cool to test our code on win32...

**Comment by zixia** [comment]
I just setup a appveyor.yml and it's live here(with a failure)
https://ci.appveyor.com/project/zixia/ps-tree

then I saw you already have a .appveyor.yml file.

I thought your .appveyor.yml will not work, because doc says the filename without the pre-dot?

**Pull request merged**
